language:
  scalars:
    String: string
    Float: float64
    Boolean: bool
    Int: int
    ID: string
  root:
    - Query
    - Mutation
    - Subscription
templates:
  - Definitions
  - Adapters
  - Provider
  - Models
config:
  pkg: "graphql"
  imports: |
      "github.com/graphql-go/graphql"
      "github.com/mitchellh/mapstructure"
formatter:
  cmd: "gofmt"
  args:
    - "-w"
    - "{{output}}"
