language:
  scalars:
    String: string
    Float: float64
    Boolean: bool
    Int: int
    ID: string
  core:
    - Query
    - Mutation
    - Subscription
generator:
  definition:
    prefix: Def
    filename: definitions.go
  adapter:
    prefix: Adp
    filename: adapters.go
  provider:
    prefix: pro
    filename: provider.go
config:
  pkg: "graphql"
  imports:
    - "github.com/graphql-go/graphql"
    - "github.com/mitchellh/mapstructure"
formatter:
  cmd: "gofmt"
  args:
    - "-w"
    - "{{output}}"
