language:
  scalars:
    String: string
    Float: float64
    Boolean: bool
    Int: int
    ID: string
  core:
    - Query
    - Mutation
    - Subscription
templates:
  - Header
  - Boilerplate
generator:
  - prefix: Def_
    filename: definitions.go
  - prefix: Adp_
    filename: adapters.go
  - prefix: Pro_
    filename: provider.go
config:
  pkg: "graphql"
  imports: |
      "github.com/graphql-go/graphql"
      "github.com/mitchellh/mapstructure"
formatter:
  cmd: "gofmt"
  args:
    - "-w"
    - "{{output}}"
